language: objective-c
xcode_project: MonitoringApplication.xcodeproj

branches:
 only:
 - master

osx_image: xcode8.3

script:
- xcodebuild clean build test -project MonitoringApplication.xcodeproj -scheme MonitoringApplicationTests

after_success:
  - bash <(curl -s https://codecov.io/bash)
